# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export DOTNET_ROOT=$HOME/repos/dotnet

ZSH_THEME="af-magic" # set by `omz`


if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

alias edit=$EDITOR

# WSL Variables for GEL1445 hostname
export KUBECONFIG="/mnt/c/Users/DerekStritzel/.kube/config"
export AWS_CONFIG_FILE="/mnt/c/Users/DerekStritzel/.aws/config"
export AWS_PROFILE="GBE-Prod"
export BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
alias open='cmd.exe /C start'

if [[ -f $HOME/.zsh_aliases ]]; then
  . $HOME/.zsh_aliases
fi

function urldecode() {
    : "${*//+/ }"  # Replace '+' with space
    echo -e "${_//%/\\x}" # Convert %XX to their ASCII equivalent
}

export PATH=$PATH:/usr/local/go/bin
source ~/.antidote/antidote.zsh
antidote load

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
